controller_list:
 - name: arm_trajectory_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
     - shoulder_pan_joint
     - shoulder_lift_joint
     - elbow_joint
     - wrist_1_joint
     - wrist_2_joint
     - wrist_3_joint
 - name: hand_trajectory_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
     - FFJ4
     - FFJ3
     - FFJ2
     - FFJ1
     - LFJ5
     - LFJ4
     - LFJ3
     - LFJ2
     - LFJ1
     - MFJ4
     - MFJ3
     - MFJ2
     - MFJ1
     - RFJ4
     - RFJ3
     - RFJ2
     - RFJ1
     - THJ5
     - THJ4
     - THJ3
     - THJ2
     - THJ1
     - WRJ2
     - WRJ1
