controller_list:
  - name: fake_arm_controller
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: fake_hand_controller
    joints:
      - WRJ2
      - WRJ1
      - FFJ4
      - FFJ3
      - FFJ2
      - FFJ1
      - LFJ5
      - LFJ4
      - LFJ3
      - LFJ2
      - LFJ1
      - MFJ4
      - MFJ3
      - MFJ2
      - MFJ1
      - RFJ4
      - RFJ3
      - RFJ2
      - RFJ1
      - THJ5
      - THJ4
      - THJ3
      - THJ2
      - THJ1
  - name: fake_armpalm_controller
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
      - WRJ2
      - WRJ1
  - name: fake_first_finger_controller
    joints:
      - FFJ4
      - FFJ3
      - FFJ2
      - FFJ1
  - name: fake_middle_finger_controller
    joints:
      - MFJ4
      - MFJ3
      - MFJ2
      - MFJ1
  - name: fake_ring_finger_controller
    joints:
      - RFJ4
      - RFJ3
      - RFJ2
      - RFJ1
  - name: fake_little_finger_controller
    joints:
      - LFJ5
      - LFJ4
      - LFJ3
      - LFJ2
      - LFJ1
  - name: fake_thumb_controller
    joints:
      - THJ5
      - THJ4
      - THJ3
      - THJ2
      - THJ1
